import type { Metadata } from 'next';
import { Open_Sans } from 'next/font/google';
import './globals.css';
import Provider from '@/components/provider';
import { cn } from '@/services/lib/utils';
import MainWrapper from '@/components/Layout/MainWrapper';

const openSans = Open_Sans({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en' suppressHydrationWarning>
      <body
        className={cn(
          'flex flex-col min-h-screen bg-background antialiased',
          openSans.className
        )}>
        <Provider>
          <MainWrapper>{children}</MainWrapper>
        </Provider>
      </body>
    </html>
  );
}
